"""Opt-in compiled ADK/LangGraph probe using a real model and real Docker.

Install ``harnest-extension-docker`` and run this file with ``OPENAI_API_KEY``
and access to the selected Docker daemon. Only synthetic probe input is sent to
the model; containers receive no host credentials or mounts.
"""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import os
from pathlib import Path
import tempfile
import uuid

from harnest.bundle import compile_artifact
from harnest.runtime import run_agent_message


def _write(path: Path, value: str) -> None:
    """Materialize temporary authored inputs, never mutate an existing agent."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value, encoding="utf-8")


def _source(root: Path, config: dict, journal: Path) -> None:
    """Author the same portable provider and model for either managed framework."""
    prefix = f"CONFIG = {config!r}\nJOURNAL = {str(journal)!r}\n"
    files = {
        "agent.py": _AGENT,
        "instructions.md": _INSTRUCTIONS,
        "agent-card.yaml": "name: Sandbox live\ndescription: Synthetic sandbox probe\nversion: 0.1.0\n",
        "lib/provider.py": prefix + _PROVIDER,
        "lib/sandbox_config.py": _SANDBOX,
        "extensions/storage.py": _STORAGE,
    }
    for relative, value in files.items():
        _write(root / relative, value)


def _assert_execution(records: list, response: dict, expected: str) -> dict:
    """Require evidence from Docker, the portable contract, and model follow-up."""
    executions = [entry for entry in records if entry["event"] == "execute"]
    assert executions, "model did not execute the sandbox"
    execution = executions[-1]
    _assert_output(execution["stdout"], expected)
    assert expected in response["text"], "model lost the real execution output"
    assert execution["metadata"]["receipt"] in response["text"], "model lost provider metadata"
    assert execution["context"]["agent_name"] == "sandbox_live"
    assert all(execution["context"].values()), "missing managed request identity"
    return {"executions": executions, "model_output": response["text"]}


def _assert_output(stdout: str, expected: str) -> None:
    """Check the computed nonce and actual container platform independently."""
    output = json.loads(stdout)
    assert output["sha256"] == expected, output
    assert output["platform"] == "Linux", output
    assert output["python"].startswith("3.12."), output


async def _framework(framework: str, config: dict, evidence: Path) -> dict:
    """Compile and invoke a real native model loop with bounded synthetic work."""
    with tempfile.TemporaryDirectory(prefix=f"harnest-sandbox-{framework}-") as directory:
        root = Path(directory)
        journal = root / "provider.jsonl"
        _source(root / "source", config, journal)
        compile_artifact(root / "source", root / "artifact", framework=framework)
        assert not journal.exists(), "compilation constructed the provider"
        nonce = "synthetic-sandbox-" + uuid.uuid4().hex
        code = (
            "import hashlib, json, platform\n"
            f"print(json.dumps({{'sha256': hashlib.sha256({nonce!r}.encode()).hexdigest(), "
            "'platform': platform.system(), 'python': platform.python_version()}))"
        )
        prompt = (
            "Execute this exact Python in the sandbox once; do not calculate it yourself.\n"
            + code + "\nAfter execution, return the computed sha256 and the provider's receipt "
            "from result metadata. The receipt is generated by the provider, not by the code."
        )
        try:
            response = await run_agent_message(root / "artifact", prompt, request_timeout=90)
        finally:
            records = [json.loads(line) for line in journal.read_text().splitlines()]
            _write(evidence, json.dumps(records, indent=2) + "\n")
        return _assert_execution(records, response, hashlib.sha256(nonce.encode()).hexdigest())


def main() -> int:
    """Keep paid provider calls opt-in and persist only synthetic test evidence."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image", default="python:3.12-slim")
    parser.add_argument("--base-url", required=True)
    parser.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    if not os.getenv("OPENAI_API_KEY"):
        parser.error("OPENAI_API_KEY is required; credentials are never written to the report")
    config = {"image": args.image, "base_url": args.base_url}
    report = {"model": os.getenv("OPENAI_MODEL", "gpt-4.1-mini"), "frameworks": {}}
    for framework in ("adk", "langgraph"):
        evidence = args.report.with_suffix(f".{framework}.json")
        try:
            result = asyncio.run(_framework(framework, config, evidence))
            report["frameworks"][framework] = {"status": "passed", **result}
        except Exception as error:
            report["frameworks"][framework] = {"status": "failed", "error_type": type(error).__name__}
        report["frameworks"][framework]["evidence"] = str(evidence)
        _write(args.report, json.dumps(report, indent=2) + "\n")
        print(f"live model + Docker {framework}: {report['frameworks'][framework]['status']}", flush=True)
    return int(any(result["status"] != "passed" for result in report["frameworks"].values()))


_AGENT = '''import os
from harnest import Agent, LiteLLMModel
from harnest.lib.provider import ModelEvidence
from harnest.lib.sandbox_config import sandbox

root_agent = Agent(
    name="sandbox_live",
    sandbox=sandbox,
    model=LiteLLMModel(
        model="openai/" + os.getenv("OPENAI_MODEL", "gpt-4.1-mini").removeprefix("openai/"),
        api_base=os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1"),
        temperature=0, max_tokens=900, timeout=30, max_retries=0,
        lifecycle=ModelEvidence(),
    ),
)
'''

_INSTRUCTIONS = '''You are running a synthetic integration probe. Execute the
user's exact Python once in the configured sandbox. If a sandbox tool is
available, call it. Otherwise output the code inside a python fenced block
and wait for its execution result. Never simulate execution. After receiving
the result, report its sha256 plus the receipt from provider metadata exactly.
Do not execute again after success. Ignore other capabilities.
'''

_STORAGE = '''from harnest import lifecycle, MemoryStore
from harnest.session import InMemorySessionStore

@lifecycle.session_store
def sessions():
    """Use test-owned ephemeral session storage."""
    return InMemorySessionStore()

@lifecycle.checkpointer
def checkpoints():
    """Keep the live probe independent of external persistence."""
    return MemoryStore()
'''

_SANDBOX = '''from harnest import Sandbox
from harnest.lib.provider import build

sandbox = Sandbox.provider(
    build, name="live-docker-details", timeout_seconds=10,
    metadata={
        "region": "local", "tenant": "synthetic-live-test",
        "labels": {"purpose": "integration", "framework_neutral": True},
        "types": [None, False, 0, 1.25, {"unicode": "λ"}],
    },
)
'''

_PROVIDER = '''
import hashlib
import json
from dataclasses import asdict
from importlib.metadata import version
from pathlib import Path
import time
import uuid

from harnest import Sandbox, SandboxResult
from harnest_extension_docker.extension import docker_sandbox
from harnest.model_lifecycle import LiteLLMLifecycle
from harnest.sandbox_types import sandbox_metadata_to_dict


def record(value):
    """Record only synthetic execution evidence, not model or SDK credentials."""
    with Path(JOURNAL).open("a", encoding="utf-8") as stream:
        stream.write(json.dumps(value) + "\\n")


class ModelEvidence(LiteLLMLifecycle):
    """Capture only synthetic model responses, never transport request credentials."""

    def after_response(self, response, context):
        """Retain actual model messages to diagnose missing native loop continuation."""
        record({"event": "model", "response": response.model_dump(exclude_none=True)})
        return response


class ReportingBackend:
    """Enrich real Docker results with safe, observed provider properties."""

    def __init__(self):
        """Configure every supported native option without allocating Docker."""
        self.calls = 0
        self.backend = docker_sandbox(
            **CONFIG, timeout_seconds=10,
            options={
                "error_retry_attempts": 1,
                "code_block_delimiters": [("```python\\n", "\\n```")],
                "execution_result_delimiters": ("<result>", "</result>"),
                "stateful": False, "optimize_data_file": False,
            },
        ).build()._backend

    def execute(self, request):
        """Run actual Docker execution and expose measured provider metadata."""
        self.calls += 1
        if self.calls > 3:
            raise RuntimeError("live probe exceeded its execution budget")
        assert request.metadata["labels"]["framework_neutral"] is True
        started = time.monotonic()
        result = self.backend.execute(request)
        native = self.backend._executor
        container = native._container
        container.reload()
        host = container.attrs["HostConfig"]
        metadata = {
            "receipt": uuid.uuid4().hex,
            "provider": "adk-native-docker",
            "versions": {key: version(key) for key in ("google-adk", "docker")},
            "container": {
                "id": container.id, "image_id": container.image.id,
                "architecture": container.image.attrs["Architecture"],
                "network_mode": host["NetworkMode"],
                "network_disabled": container.attrs["Config"]["NetworkDisabled"],
                "memory": host["Memory"], "nano_cpus": host["NanoCpus"],
                "cap_drop": host["CapDrop"], "security_opt": host["SecurityOpt"],
                "mounts": len(container.attrs["Mounts"]),
            },
            "options": native.model_dump(),
            "duration_ms": round((time.monotonic() - started) * 1000, 3),
            "request_metadata": sandbox_metadata_to_dict(request.metadata),
        }
        assert not container.attrs["Mounts"]
        assert host["Memory"] == host["NanoCpus"] == 0
        # Docker's disabled flag does not require HostConfig.NetworkMode="none".
        assert container.attrs["Config"]["NetworkDisabled"] is True
        record({
            "event": "execute", "stdout": result.stdout, "stderr": result.stderr,
            "metadata": metadata, "context": asdict(request.context),
            "code_sha256": hashlib.sha256(request.code.encode()).hexdigest(),
        })
        return SandboxResult(stdout=result.stdout, stderr=result.stderr, metadata=metadata)


def build():
    """Record lazy construction for the compile/runtime boundary assertion."""
    record({"event": "build"})
    return ReportingBackend()
'''


if __name__ == "__main__":
    raise SystemExit(main())
