import {build} from 'esbuild';
import {readFile,readdir,writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';

const root=fileURLToPath(new URL('.',import.meta.url));
await build({absWorkingDir:root,entryPoints:['editor.js'],bundle:true,format:'esm',minify:true,
  legalComments:'inline',outfile:'../src/harnest_builder/ui_packs/default/assets/editor.js',
  banner:{js:'/* Generated by studio/frontend/build.mjs. Third-party licenses: editor.LICENSE.txt. */'}});
const lock=JSON.parse(await readFile(new URL('package-lock.json',import.meta.url),'utf8'));
const notices=[];
for(const [path,metadata] of Object.entries(lock.packages)) {
  if(!path||metadata.dev)continue;
  const directory=new URL(`${path}/`,import.meta.url);
  const name=(await readdir(directory)).find(file=>/^licen[sc]e(?:\.|$)/i.test(file));
  if(!name)throw new Error(`Missing license for ${path}`);
  notices.push(`${path.replace(/^node_modules\//,'')} ${metadata.version}\n\n${await readFile(new URL(name,directory),'utf8')}`);
}
await writeFile(new URL('../src/harnest_builder/ui_packs/default/assets/editor.LICENSE.txt',import.meta.url),notices.join('\n\n---\n\n'));
